### ISSUE TITLE
Placeholder - add to fint-min.css

### ISSUE THREAD

**Issue by TheFlessenkemperInitiative** [TheFlessenkemperInitiative/fint#7]
```css
::placeholder 
{
  color: inherit;
}
```
